// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQW-YaySbIf-sInVF3grDx-Mgs0DdwoJg',
    appId: '1:58644050606:web:ba97eacc700f34a297333f',
    messagingSenderId: '58644050606',
    projectId: 'todo-10101',
    authDomain: 'todo-10101.firebaseapp.com',
    storageBucket: 'todo-10101.appspot.com',
    measurementId: 'G-BNYCC40P5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe9k_i7j-sUowohSCnh8xQR1aabI_ZLpI',
    appId: '1:58644050606:android:b6508903c67e8e8197333f',
    messagingSenderId: '58644050606',
    projectId: 'todo-10101',
    storageBucket: 'todo-10101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChgOLFyctDIlo_RQlZEqYJPG6AfvVLdGY',
    appId: '1:58644050606:ios:7a65d3d46f7e9cc897333f',
    messagingSenderId: '58644050606',
    projectId: 'todo-10101',
    storageBucket: 'todo-10101.appspot.com',
    iosClientId: '58644050606-1b9kb4a8rqlgnm6aeaicl66a8ego1so5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
